name: Docker Build Push
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      push:
        required: false
        default: true
        type: boolean
      jib:
        required: false
        default: false
        type: boolean
    secrets:
      acr-client-id:
        required: true
      acr-password:
        required: true
      auth-token:
        required: false

jobs:
  docker-build:
    if: ${{ !inputs.jib }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate DateTime
        run: |
          echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: beezlabs.azurecr.io
          username: ${{ secrets.acr-client-id }}
          password: ${{ secrets.acr-password }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: ${{ inputs.push }}
          tags: beezlabs.azurecr.io/containers/beezlabs/${{ github.event.repository.name }}:${{ inputs.version }}
          labels: |
            org.opencontainers.image.created=${{ env.NOW }}
            org.opencontainers.image.version=${{ inputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
          secrets: |
            "NPM_TOKEN=//npm.pkg.github.com/:_authToken=${{ secrets.auth-token }}
            @beezlabs-org:registry=https://npm.pkg.github.com/
            GO_PRIVATE_SECRET=${{ secrets.auth-token }}"

  jib-build:
    if: ${{ inputs.jib }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Jib Build
        env:
          IMAGE_TAG: beezlabs.azurecr.io/containers/beezlabs/${{ github.event.repository.name }}:${{ inputs.version }}
          ACR_CLIENT_ID: ${{ secrets.acr-client-id }}
          ACR_PASSWORD: ${{ secrets.acr-password }}
          GPR_USERNAME: beezlabs
          GPR_PASSWORD: ${{ secrets.auth-token }}
        run: |
          ./gradlew jib
