name: Docker Build Push
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      push:
        required: false
        default: true
        type: boolean
    secrets:
      acr-client-id:
        required: true
      acr-password:
        required: true
      auth-token:
        required: false

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: beezlabs.azurecr.io
          username: ${{ secrets.acr-client-id }}
          password: ${{ secrets.acr-password }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: ${{ inputs.push }}
          tags: beezlabs.azurecr.io/containers/beezlabs/${{ github.event.repository.name }}:${{ inputs.version }}
          secrets: |
            "NPM_TOKEN=//npm.pkg.github.com/:_authToken=${{ secrets.auth-token }}
            @beezlabs-org:registry=https://npm.pkg.github.com/
            GO_PRIVATE_SECRET=${{ secrets.auth-token }}"
